# Uncomment the next line to define a global platform for your project
platform :osx, '10.12'

use_frameworks! # Add this if you are targeting iOS 8+ or using Swift
pod 'CocoaAsyncSocket'  

pod 'OSCKit'

target 'bleosc' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for bleosc

end
